name: AutoTweet

on:
  schedule:
    - cron: "0 */8 * * *"  # Ejecuta cada 8 horas
  workflow_dispatch:

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install tweepy

      - name: Run bot
        run: python twitter_bot.py
